name: 'main'

on:
  push:

jobs:
  scratchpad:
    runs-on: ubuntu-latest
    env:
      artifact-name-1: $GITHUB_RUN_NUMBER
      artifact-name-2: ${GITHUB_RUN_NUMBER}
      artifact-name-3: ${github.GITHUB_RUN_NUMBER}

    defaults:
    steps:
    - name: Print
      run: |
        env

        echo ${{ env.artifact-name-1 }}
        echo ${{ env.artifact-name-2 }}
        echo ${{ env.artifact-name-3 }}
