name: 'main'

on:
  push:

jobs:
  scratchpad:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        run_id: [1, 2]
    env:
      artifact-name-1: $GITHUB_RUN_NUMBER
      artifact-name-2: ${GITHUB_RUN_NUMBER}
      artifact-name-3: sl-$GITHUB_RUN_NUMBER-${{ matrix.run_id }}

    steps:
    - name: Print
      run: |
        env

        echo artifact-name-1=${{ env.artifact-name-1 }}
        echo artifact-name-2=${{ env.artifact-name-2 }}
        echo artifact-name-3=${{ env.artifact-name-3 }}
