name: 'main'

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:

jobs:
  scratchpad:
    name: "Linux | Install | ${{ matrix.run_id }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Get top commit details
      uses: actions/github-script@v6.4.0
      id: author-date
      with:
        script: |
          const commit_details = await github.rest.repos.getCommit({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: context.sha });
          return commit_details.data.commit.author.date

    - name: Print
      run: |
        export COMMITTED_AT=$(date -d ${{ steps.author-date.outputs.result }} +'%Y.%m.%d_%H.%M.%S')
        echo COMMITTED_AT-1=$COMMITTED_AT
        echo COMMITTED_AT=2=${{ env.COMMITTED_AT }}

